services:
  mysql:
    image: mysql:8.4
    container_name: velocitycar-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: velocitycar
      MYSQL_USER: velocity
      MYSQL_PASSWORD: velocity123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: ${API_IMAGE:-seuusuario/velocitycar-api:1.0}
    container_name: velocitycar-api
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/velocitycar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: velocity
      SPRING_DATASOURCE_PASSWORD: velocity123
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"

volumes:
  mysql_data:
